### ISSUE TITLE
aznbsetup

### ISSUE THREAD

**Issue by yn-coder** [yn-coder/CodingTeacherJupyter#1]
```
nbuser@nbserver:~$ cat .nb.setup.log
Running setup script at /home/nbuser/library/aznbsetup.sh at Sat Jul 14 14:12:59 UTC 2018
fatal: Not a git repository (or any of the parent directories): .git
Copying: coding_teacher_ext -> /home/nbuser/.local/share/jupyter/nbextensions/coding_teacher_ext
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 199, in install_nbextension
    _maybe_copy(src, full_dest, logger=logger)
  File "/usr/local/lib/python2.7/dist-packages/notebook/nbextensions.py", line 1046, in _maybe_copy
    shutil.copy2(src, dest)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'coding_teacher_ext'
Enabling common extension coding_teacher_ext/main...
      - Validating: problems found:
        - require?  X coding_teacher_ext/main
Done initial azure notebooks environment setup
```

**Comment by yn-coder** [comment]
now working

**Comment by yn-coder** [comment]
```
nbuser@nbserver:~$ cat .nb.setup.log
Running setup script at /home/nbuser/library/aznbsetup.sh at Sat Jul 14 14:46:11 UTC 2018
Already up-to-date.
Making directory: /home/nbuser/.local/share/jupyter/nbextensions/coding_teacher_ext/
Copying: /home/nbuser/library/coding_teacher_ext/main.js -> /home/nbuser/.local/share/jupyter/nbextensions/coding_teacher_ext/main.js

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable <the entry point> --user

Enabling common extension coding_teacher_ext/main...
      - Validating: OK
Done initial azure notebooks environment setup
```
